//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestaEP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_EncuestasEntities : DbContext
    {
        public Db_EncuestasEntities()
            : base("name=Db_EncuestasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campos> Campos { get; set; }
        public virtual DbSet<Encuesta> Encuesta { get; set; }
        public virtual DbSet<Respuesta_Detalle> Respuesta_Detalle { get; set; }
        public virtual DbSet<Respuesta_Encabezado> Respuesta_Encabezado { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
