//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta_Detalle
    {
        public int id { get; set; }
        public int id_campo { get; set; }
        public string valor { get; set; }
        public int id_encabezado { get; set; }
    
        public virtual Campos Campos { get; set; }
        public virtual Respuesta_Encabezado Respuesta_Encabezado { get; set; }
    }
}
