//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta_Encabezado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respuesta_Encabezado()
        {
            this.Respuesta_Detalle = new HashSet<Respuesta_Detalle>();
        }
    
        public int id { get; set; }
        public int id_encuesta { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Encuesta Encuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta_Detalle> Respuesta_Detalle { get; set; }
    }
}
